// ============================================================
// DASHBOARD.JS – ATS Placement Dashboard (Live Google Sheets)
// ============================================================

// ── Configuration ────────────────────────────────────────────
const SHEET_CONFIG = {
    sheetId: "15sg6jNezpFpz7v-vrtFH2_vBnr8NqHNp10gK-rZrRpM",
    gid: 0,
    pollInterval: 15000, // 15 seconds for more responsive updates
};

// Column mapping — positional (0-indexed), matches sheet column order A→N
// A=Timestamp  B=Company Name  C=Placement Cycle  D=Company+Cycle
// E=Job Role   F=Seniority     G=Location         H=CTC
// I=Eligibility  J=Skills  K=Tools  L=Complexity  M=Generated By  N=Target School
const COL_MAP = {
    timestamp: 0,    // A
    company: 1,      // B
    cycle: 2,        // C
    companyCycle: 3, // D
    role: 4,         // E
    seniority: 5,    // F
    location: 6,     // G
    ctc: 7,          // H
    eligibility: 8,  // I
    skills: 9,       // J
    tools: 10,       // K
    complexity: 11,  // L
    generatedBy: 12, // M
    school: 13,      // N ← Target School
};

// ── State ────────────────────────────────────────────────────
let SHEET_DATA = [];
let lastDataHash = "__UNINITIALISED__"; // Sentinel so first fetch always triggers render
let pollTimer = null;
let autoRefreshEnabled = true;

// ── Color palette ────────────────────────────────────────────
const COLORS = {
    teal: "rgba(99,102,241,1)",
    tealSoft: "rgba(99,102,241,0.15)",
    amber: "rgba(249,115,22,1)",
    amberSoft: "rgba(249,115,22,0.15)",
    blue: "rgba(59,130,246,1)",
    violet: "rgba(139,92,246,1)",
    rose: "rgba(244,63,94,1)",
    emerald: "rgba(16,185,129,1)",
    slate: "rgba(100,116,139,1)",
    palette: [
        "rgba(99,102,241,0.85)",
        "rgba(249,115,22,0.85)",
        "rgba(16,185,129,0.85)",
        "rgba(139,92,246,0.85)",
        "rgba(244,63,94,0.85)",
        "rgba(59,130,246,0.85)",
        "rgba(245,158,11,0.85)",
        "rgba(168,85,247,0.85)",
        "rgba(236,72,153,0.85)",
        "rgba(14,165,233,0.85)",
        "rgba(217,70,239,0.85)",
        "rgba(100,116,139,0.85)",
    ],
    paletteSoft: [
        "rgba(99,102,241,0.15)",
        "rgba(249,115,22,0.15)",
        "rgba(16,185,129,0.15)",
        "rgba(139,92,246,0.15)",
        "rgba(244,63,94,0.15)",
        "rgba(59,130,246,0.15)",
        "rgba(245,158,11,0.15)",
        "rgba(168,85,247,0.15)",
        "rgba(236,72,153,0.15)",
        "rgba(14,165,233,0.15)",
        "rgba(217,70,239,0.15)",
        "rgba(100,116,139,0.15)",
    ],
};

// ── Chart.js global defaults ─────────────────────────────────
Chart.defaults.font.family = "'Inter', 'IBM Plex Sans', sans-serif";
Chart.defaults.color = "#6b7280";
Chart.defaults.plugins.legend.labels.usePointStyle = true;
Chart.defaults.plugins.legend.labels.padding = 14;

// ── Google Sheets Fetch (via backend proxy to bypass Google's CDN cache) ─────
// Previously we fetched gviz/tq directly from the browser.  Google's CDN caches
// those responses for several minutes — so deleting rows from the sheet would
// not immediately reflect in the dashboard.
// Now we route through our own backend (/api/sheet-data) which:
//   1. Makes a server-side request with Cache-Control: no-cache headers
//   2. Returns the response with Cache-Control: no-store so the browser also
//      never caches it
// This guarantees that what the sheet contains RIGHT NOW is what we display.
async function fetchSheetData() {
    // Use a random cache-buster on our own proxy too, just to be safe
    const bust = `${Date.now()}_${Math.random().toString(36).slice(2)}`;
    const url  = `/api/sheet-data?gid=${SHEET_CONFIG.gid}&_=${bust}`;

    const response = await fetch(url, {
        cache: "no-store",   // Instruct the browser fetch cache to skip storage
        headers: {
            "Cache-Control": "no-cache",
            "Pragma":        "no-cache",
        },
    });

    if (!response.ok) {
        const errJson = await response.json().catch(() => ({}));
        throw new Error(errJson.error || `Proxy returned HTTP ${response.status}. Check that the server is running.`);
    }

    const json = await response.json();

    if (json.status === "error") {
        throw new Error(json.errors?.map(e => e.message).join(", ") || "Google Sheets API error");
    }

    const rows = json.table?.rows || [];
    const data = [];

    for (const row of rows) {
        const cells = row.c || [];
        const getValue = (idx) => {
            const cell = cells[idx];
            if (!cell) return "";
            // Use formatted value (f) if available, otherwise raw value (v)
            return (cell.f || cell.v || "").toString().trim();
        };

        const timestamp = getValue(COL_MAP.timestamp);
        const company   = getValue(COL_MAP.company);
        if (!company) continue; // Skip empty rows

        const roleVal = getValue(COL_MAP.role);
        const skillsVal = getValue(COL_MAP.skills);
        const eligibilityVal = getValue(COL_MAP.eligibility);
        const schoolValRaw = getValue(COL_MAP.school);
        const schoolVal = schoolValRaw || classifySchoolHeuristically(
            { role: roleVal, skills: skillsVal },
            roleVal + " " + skillsVal + " " + eligibilityVal
        );

        data.push({
            timestamp,
            company,
            cycle: getValue(COL_MAP.cycle),
            companyCycle: getValue(COL_MAP.companyCycle),
            role: roleVal,
            seniority: getValue(COL_MAP.seniority),
            location: getValue(COL_MAP.location),
            ctc: getValue(COL_MAP.ctc),
            eligibility: eligibilityVal,
            skills: skillsVal,
            tools: getValue(COL_MAP.tools),
            complexity: getValue(COL_MAP.complexity),
            generatedBy: getValue(COL_MAP.generatedBy),
            school: schoolVal,
        });
    }

    return { data, table: json.table || { cols: [], rows: [] }, _needsRedeploy: json._needsRedeploy || false, _source: json._source || "unknown" };
}


// Simple hash to detect data changes.
// IMPORTANT: empty arrays must NOT hash to "" — that equals the sentinel
// and would suppress the very first render when the sheet is empty.
function hashData(data) {
    if (data.length === 0) return "__EMPTY__";
    return data.map(d => `${d.timestamp}|${d.company}|${d.role}`).join("##");
}

// ── Helpers ──────────────────────────────────────────────────
function countBy(arr, key) {
    const map = {};
    arr.forEach(item => {
        const val = (item[key] || "Unknown").trim();
        map[val] = (map[val] || 0) + 1;
    });
    return map;
}

function uniqueValues(arr, key) {
    return [...new Set(arr.map(i => (i[key] || "Unknown").trim()))];
}

function classifyCourseToSchool(courseName) {
    const c = courseName.toLowerCase().trim();

    // School of Engineering (SOE)
    if (/\b(b\.?tech|m\.?tech|b\.?e\.?|m\.?e\.?|b\.?c\.?a\.?|m\.?c\.?a\.?|cse|computer|software|engineering|devops|cloud|it|information\s*technology|ece|electronics|mechanical|civil|electrical|aerospace|data\s*engineering|b\.?sc|m\.?sc|science|math|statistics|stat|data\s*science|data\s*analyst|llb|llm|law|legal|ba|ma|arts|design|humanities|psychology)\b/i.test(c)) {
        // Science/Law/Humanities courses default to SOE unless business pattern matches
        if (/\b(mba|bba|pgdm|b\.?com|m\.?com|finance|management|marketing|business|commerce|accounting|hr|recruiting|sales|bms)\b/i.test(c)) {
            return "School of Business (SOB)";
        }
        return "School of Engineering (SOE)";
    }

    // School of Business (SOB)
    if (/\b(mba|bba|pgdm|b\.?com|m\.?com|finance|management|marketing|business|commerce|accounting|hr|recruiting|sales|bms)\b/i.test(c)) {
        return "School of Business (SOB)";
    }

    // Fallback keyword matching
    if (/business|commerce|manag|market|finance|sales|hr\b/i.test(c)) return "School of Business (SOB)";

    return "School of Engineering (SOE)"; // Safe default
}

function extractCoursesHeuristically(text) {
    if (!text) return [];
    const coursesFound = new Set();

    const pattern = /\b(b\.?\s*tech|m\.?\s*tech|b\.?\s*e|m\.?\s*e|b\.?\s*c\.?\s*a|m\.?\s*c\.?\s*a|m\.?\s*b\.?\s*a|b\.?\s*b\.?\s*a|b\.?\s*com|m\.?\s*com|b\.?\s*sc|m\.?\s*sc|ph\.?\s*d|l\.?\s*l\.?\s*b|l\.?\s*l\.?\s*m|b\.?\s*a|m\.?\s*a|pgdm)\b/gi;
    const branchPattern = /\b(b\.?\s*tech|m\.?\s*tech|b\.?\s*e|m\.?\s*e|mba|mca|bca|bsc|msc|bba)\b\s*\(?[a-z\s]{2,10}\)?/gi;

    let match;
    while ((match = branchPattern.exec(text)) !== null) {
        coursesFound.add(match[0].trim());
    }

    while ((match = pattern.exec(text)) !== null) {
        const course = match[1].trim();
        let normalized = course.replace(/\s+/g, "").toUpperCase();

        if (normalized.startsWith("B") && normalized.endsWith("TECH")) normalized = "B.Tech";
        else if (normalized.startsWith("M") && normalized.endsWith("TECH")) normalized = "M.Tech";
        else if (normalized === "MBA") normalized = "MBA";
        else if (normalized === "MCA") normalized = "MCA";
        else if (normalized === "BCA") normalized = "BCA";
        else if (normalized === "BE") normalized = "B.E.";
        else if (normalized === "ME") normalized = "M.E.";
        else if (normalized.startsWith("B") && normalized.endsWith("SC")) normalized = "B.Sc";
        else if (normalized.startsWith("M") && normalized.endsWith("SC")) normalized = "M.Sc";
        else if (normalized === "BBA") normalized = "BBA";
        else if (normalized.startsWith("B") && normalized.endsWith("COM")) normalized = "B.Com";
        else if (normalized.startsWith("M") && normalized.endsWith("COM")) normalized = "M.Com";
        else if (normalized === "PHD" || normalized === "PH.D") normalized = "PhD";
        else if (normalized === "LLB") normalized = "LLB";
        else if (normalized === "LLM") normalized = "LLM";
        else if (normalized === "BA") normalized = "BA";
        else if (normalized === "MA") normalized = "MA";
        else if (normalized === "PGDM") normalized = "PGDM";

        let alreadyExists = false;
        for (const existing of coursesFound) {
            if (existing.replace(/\s+/g, "").toUpperCase().includes(normalized.replace(/\./g, "").toUpperCase())) {
                alreadyExists = true;
                break;
            }
        }
        if (!alreadyExists) {
            coursesFound.add(normalized);
        }
    }

    return Array.from(coursesFound);
}

function renderSchoolBadges(primarySchool, eligibility, role) {
    const schools = new Set();
    
    if (primarySchool && primarySchool.includes("School")) {
        schools.add(primarySchool);
    }

    const textToScan = `${eligibility || ""} ${role || ""}`;
    const courses = extractCoursesHeuristically(textToScan);
    for (const course of courses) {
        schools.add(classifyCourseToSchool(course));
    }

    if (schools.size === 0) {
        schools.add(primarySchool || "School of Engineering (SOE)");
    }

    return Array.from(schools).map(school => {
        const cls = school.toLowerCase().replace(/[^a-z0-9]/g, '_');
        return `<span class="school-badge ${cls}" style="margin: 2px 4px 2px 0;">${school}</span>`;
    }).join(" ");
}

function classifySchoolHeuristically(result, jdText) {
    // Only SOE and SOB are active schools.
    const role   = (result.role || "").toLowerCase().trim();
    const cat    = (result.category || result.cat || "").toLowerCase().trim();
    const skills = (result.skills || "").toLowerCase();
    const tools  = (result.tools || "").toLowerCase();
    const combined = `${role} ${cat} ${skills} ${tools}`;

    // ── SOB — School of Business ─────────────────────────────
    const sobRoleTerms = [
        "business analyst","product manager","marketing","sales",
        "finance","accounting","accountant","operations manager",
        "supply chain","logistics","brand manager","growth",
        "strategy","management consultant","investment","equity",
        "trading","audit","tax","treasury","hr manager",
        "human resource","recruiter","talent acquisition",
        "customer success","account manager","business development",
        "ceo","cfo","coo","management trainee","trainee"
    ];
    const sobQualTerms = ["mba","bba","bcom","b.com","cfa","cpa","pgdm"];
    const sobCatTerms = [
        "business","marketing","sales","finance","management",
        "operations","consulting","strategy","human resources"
    ];
    if (
        sobRoleTerms.some(k => role.includes(k)) ||
        sobQualTerms.some(k => combined.includes(k)) ||
        sobCatTerms.some(k => cat.includes(k))
    ) return "School of Business (SOB)";

    // ── SOE — School of Engineering (default for tech, science, law, arts) ─
    return "School of Engineering (SOE)";
}


function formatDate(ts) {
    try {
        if (!ts) return "";
        let d;
        if (ts.startsWith("Date(")) {
            const matches = ts.match(/\d+/g);
            if (matches && matches.length >= 3) {
                const y = parseInt(matches[0]);
                const m = parseInt(matches[1]);
                const day = parseInt(matches[2]);
                const h = parseInt(matches[3] || "0");
                const min = parseInt(matches[4] || "0");
                const s = parseInt(matches[5] || "0");
                d = new Date(y, m, day, h, min, s);
            }
        } else if (ts.includes("/")) {
            const [datePart, timePart] = ts.split(" ");
            const parts = datePart.split("/");
            if (parts.length === 3) {
                // Handle dd/MM/yyyy format
                const [day, month, year] = parts;
                d = new Date(parseInt(year), parseInt(month) - 1, parseInt(day));
                if (timePart) {
                    const [h, m, s] = timePart.split(":");
                    d.setHours(parseInt(h) || 0, parseInt(m) || 0, parseInt(s) || 0);
                }
            }
        } else {
            d = new Date(ts.replace(" ", "T"));
        }
        if (!d || isNaN(d.getTime())) return ts;
        return d.toLocaleDateString("en-IN", {
            timeZone: "Asia/Kolkata",
            day: "2-digit",
            month: "short",
            year: "numeric"
        });
    } catch { return ts; }
}

function formatDateTime(ts) {
    try {
        if (!ts) return "";
        let d;
        if (ts.startsWith("Date(")) {
            const matches = ts.match(/\d+/g);
            if (matches && matches.length >= 3) {
                const y = parseInt(matches[0]);
                const m = parseInt(matches[1]);
                const day = parseInt(matches[2]);
                const h = parseInt(matches[3] || "0");
                const min = parseInt(matches[4] || "0");
                const s = parseInt(matches[5] || "0");
                d = new Date(y, m, day, h, min, s);
            }
        } else if (ts.includes("/")) {
            const [datePart, timePart] = ts.split(" ");
            const parts = datePart.split("/");
            if (parts.length === 3) {
                const [day, month, year] = parts;
                d = new Date(parseInt(year), parseInt(month) - 1, parseInt(day));
                if (timePart) {
                    const [h, m, s] = timePart.split(":");
                    d.setHours(parseInt(h) || 0, parseInt(m) || 0, parseInt(s) || 0);
                }
            }
        } else {
            d = new Date(ts.replace(" ", "T"));
        }
        if (!d || isNaN(d.getTime())) return ts;
        return d.toLocaleString("en-IN", {
            timeZone: "Asia/Kolkata",
            day: "2-digit",
            month: "short",
            hour: "2-digit",
            minute: "2-digit",
            hour12: true
        });
    } catch { return ts; }
}

function formatTimeAgo(date) {
    const seconds = Math.floor((new Date() - date) / 1000);
    if (seconds < 5) return "just now";
    if (seconds < 60) return `${seconds}s ago`;
    const minutes = Math.floor(seconds / 60);
    if (minutes < 60) return `${minutes}m ago`;
    const hours = Math.floor(minutes / 60);
    return `${hours}h ago`;
}

function animateValue(el, end, duration = 800) {
    let start = 0;
    const startTime = performance.now();
    function tick(now) {
        const progress = Math.min((now - startTime) / duration, 1);
        const eased = 1 - Math.pow(1 - progress, 3);
        el.textContent = Math.floor(eased * end);
        if (progress < 1) requestAnimationFrame(tick);
    }
    requestAnimationFrame(tick);
}

// ── Tab Navigation ───────────────────────────────────────────
const tabBtns   = document.querySelectorAll(".tab-btn");
const tabPanels = document.querySelectorAll(".tab-panel");
let dashboardInitialized = false;

tabBtns.forEach(btn => {
    btn.addEventListener("click", () => {
        const target = btn.dataset.tab;

        // Update button states
        tabBtns.forEach(b => {
            b.classList.remove("active");
            b.setAttribute("aria-selected", "false");
        });
        btn.classList.add("active");
        btn.setAttribute("aria-selected", "true");

        // Update panel visibility
        tabPanels.forEach(p => p.classList.remove("active"));
        const targetPanel = document.getElementById(target + "Tab");
        if (targetPanel) targetPanel.classList.add("active");

        // Initialise or refresh dashboard
        if (target === "dashboard") {
            if (!dashboardInitialized) {
                dashboardInitialized = true;
                initDashboard();
            } else {
                loadDashboardData(false);
            }
        }
    });
});

// ── Chart instances ──────────────────────────────────────────
let chartInstances = {};

function destroyCharts() {
    Object.values(chartInstances).forEach(c => c.destroy());
    chartInstances = {};
}

// ── UI State Management ──────────────────────────────────────
function showLoading() {
    const el = document.getElementById("dashLoading");
    if (el) el.classList.remove("hidden");
}

function hideLoading() {
    const el = document.getElementById("dashLoading");
    if (el) el.classList.add("hidden");
}

function showError(message) {
    const el = document.getElementById("dashError");
    if (el) {
        el.querySelector(".dash-error-msg").textContent = message;
        el.classList.remove("hidden");
    }
}

function hideError() {
    const el = document.getElementById("dashError");
    if (el) el.classList.add("hidden");
}

function updateLastUpdated() {
    const el = document.getElementById("lastUpdated");
    if (el) {
        const now = new Date();
        el.textContent = `Last updated: ${now.toLocaleTimeString("en-IN", { timeZone: "Asia/Kolkata", hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: true })}`;
        el.title = now.toLocaleString("en-IN", { timeZone: "Asia/Kolkata" });

        // Start the "ago" ticker
        clearInterval(el._agoTimer);
        el._agoTimer = setInterval(() => {
            el.textContent = `Updated ${formatTimeAgo(now)}`;
        }, 10000);
    }
}

function updateAutoRefreshUI() {
    const btn = document.getElementById("toggleAutoRefresh");
    const dot = document.getElementById("liveDot");
    if (btn) {
        btn.textContent = autoRefreshEnabled ? "Auto-refresh ON" : "Auto-refresh OFF";
        btn.classList.toggle("active", autoRefreshEnabled);
    }
    if (dot) {
        dot.classList.toggle("live", autoRefreshEnabled);
    }
}

// ── KPI Rendering ────────────────────────────────────────────
function renderKPIs(data) {
    animateValue(document.getElementById("kpiTotalValue"), data.length);
    animateValue(document.getElementById("kpiCompaniesValue"), uniqueValues(data, "company").length);
    animateValue(document.getElementById("kpiRolesValue"), uniqueValues(data, "role").length);

    // Top seniority
    const seniorityMap = countBy(data.filter(d => d.seniority), "seniority");
    const sorted = Object.entries(seniorityMap).sort((a, b) => b[1] - a[1]);
    document.getElementById("kpiSeniorityValue").textContent = sorted.length ? sorted[0][0] : "—";

    // Update additional KPIs
    const avgCtcEl = document.getElementById("kpiAvgCtcValue");
    if (avgCtcEl) {
        const ctcValues = data.map(d => parseFloat((d.ctc || "").replace(/[^\d.]/g, ""))).filter(v => !isNaN(v) && v > 0);
        avgCtcEl.textContent = ctcValues.length ? `₹${(ctcValues.reduce((a, b) => a + b, 0) / ctcValues.length).toFixed(1)}L` : "—";
    }

    const locationsEl = document.getElementById("kpiLocationsValue");
    if (locationsEl) {
        const locations = uniqueValues(data.filter(d => d.location), "location");
        animateValue(locationsEl, locations.length);
    }
}

// ── KPI Modal (Click-to-View Details) ────────────────────────
function openKpiModal(title, bodyHTML) {
    const modal = document.getElementById("kpiModal");
    const titleEl = document.getElementById("kpiModalTitle");
    const bodyEl = document.getElementById("kpiModalBody");
    if (!modal || !titleEl || !bodyEl) return;

    titleEl.textContent = title;
    bodyEl.innerHTML = bodyHTML;
    modal.classList.remove("hidden");
    document.body.style.overflow = "hidden";

    // Focus the close button
    document.getElementById("kpiModalClose")?.focus();
}

function closeKpiModal() {
    const modal = document.getElementById("kpiModal");
    if (modal) {
        modal.classList.add("hidden");
        document.body.style.overflow = "";
    }
}

// Close on overlay click
document.getElementById("kpiModal")?.addEventListener("click", (e) => {
    if (e.target.id === "kpiModal") closeKpiModal();
});

// Close on button click
document.getElementById("kpiModalClose")?.addEventListener("click", closeKpiModal);

// Close on Escape key
document.addEventListener("keydown", (e) => {
    if (e.key === "Escape") closeKpiModal();
});

// ── KPI Card Click Handlers ──────────────────────────────────
document.getElementById("kpiTotal")?.addEventListener("click", () => {
    if (SHEET_DATA.length === 0) return;
    const rows = SHEET_DATA.map((d, i) => `
        <tr>
            <td class="kpi-modal-num">${i + 1}</td>
            <td><strong>${d.company || "—"}</strong></td>
            <td>${d.role || "—"}</td>
            <td>${d.seniority || "—"}</td>
            <td>${d.timestamp ? formatDate(d.timestamp) : "—"}</td>
        </tr>
    `).join("");
    openKpiModal(
        `All Applications (${SHEET_DATA.length})`,
        `<table class="kpi-modal-table">
            <thead><tr><th>#</th><th>Company</th><th>Role</th><th>Seniority</th><th>Date</th></tr></thead>
            <tbody>${rows}</tbody>
        </table>`
    );
});

document.getElementById("kpiCompanies")?.addEventListener("click", () => {
    if (SHEET_DATA.length === 0) return;
    const companyMap = countBy(SHEET_DATA, "company");
    const sorted = Object.entries(companyMap).sort((a, b) => b[1] - a[1]);
    const rows = sorted.map(([company, count], i) => `
        <tr>
            <td class="kpi-modal-num">${i + 1}</td>
            <td><strong>${company}</strong></td>
            <td><span class="kpi-modal-count">${count} application${count > 1 ? "s" : ""}</span></td>
        </tr>
    `).join("");
    openKpiModal(
        `Unique Companies (${sorted.length})`,
        `<table class="kpi-modal-table">
            <thead><tr><th>#</th><th>Company</th><th>Applications</th></tr></thead>
            <tbody>${rows}</tbody>
        </table>`
    );
});

document.getElementById("kpiRoles")?.addEventListener("click", () => {
    if (SHEET_DATA.length === 0) return;
    const roleMap = countBy(SHEET_DATA, "role");
    const sorted = Object.entries(roleMap).sort((a, b) => b[1] - a[1]);
    const rows = sorted.map(([role, count], i) => `
        <tr>
            <td class="kpi-modal-num">${i + 1}</td>
            <td><strong>${role}</strong></td>
            <td><span class="kpi-modal-count">${count} listing${count > 1 ? "s" : ""}</span></td>
        </tr>
    `).join("");
    openKpiModal(
        `Unique Roles (${sorted.length})`,
        `<table class="kpi-modal-table">
            <thead><tr><th>#</th><th>Role</th><th>Listings</th></tr></thead>
            <tbody>${rows}</tbody>
        </table>`
    );
});

document.getElementById("kpiSeniority")?.addEventListener("click", () => {
    if (SHEET_DATA.length === 0) return;
    const seniorityMap = countBy(SHEET_DATA.filter(d => d.seniority), "seniority");
    const sorted = Object.entries(seniorityMap).sort((a, b) => b[1] - a[1]);
    const rows = sorted.map(([level, count], i) => {
        const pct = ((count / SHEET_DATA.length) * 100).toFixed(1);
        return `
            <tr>
                <td class="kpi-modal-num">${i + 1}</td>
                <td><strong>${level}</strong></td>
                <td>${count} application${count > 1 ? "s" : ""}</td>
                <td>
                    <div class="kpi-modal-bar-wrap">
                        <div class="kpi-modal-bar" style="width:${pct}%"></div>
                        <span>${pct}%</span>
                    </div>
                </td>
            </tr>
        `;
    }).join("");
    openKpiModal(
        `Seniority Breakdown`,
        `<table class="kpi-modal-table">
            <thead><tr><th>#</th><th>Seniority Level</th><th>Count</th><th>Share</th></tr></thead>
            <tbody>${rows}</tbody>
        </table>`
    );
});

// Keyboard support for KPI cards (Enter key)
document.querySelectorAll(".kpi-clickable").forEach(card => {
    card.addEventListener("keydown", (e) => {
        if (e.key === "Enter" || e.key === " ") {
            e.preventDefault();
            card.click();
        }
    });
});

// ── Chart: Applications Over Time (line) ─────────────────────
function renderTimelineChart(data) {
    const canvas = document.getElementById("timelineChart");
    if (!canvas) return;
    const existingChart = Chart.getChart(canvas);
    if (existingChart) existingChart.destroy();

    // ── Detect single-day vs multi-day ───────────────────────────
    const uniqueDays = [...new Set(data.map(d => formatDate(d.timestamp)).filter(Boolean))];
    const isSingleDay = uniqueDays.length <= 1;

    if (isSingleDay) {
        _renderHourlyBreakdown(canvas, data, uniqueDays[0]);
    } else {
        _renderMultiDayTimeline(canvas, data);
    }
}

// ── Single-day view: JDs by hour of day, grouped by school ───────
function _renderHourlyBreakdown(canvas, data, dateLabel) {
    // Parse hour from timestamp "dd/mm/yyyy HH:MM:SS"
    const hourBins = { SOE: new Array(24).fill(0), SOB: new Array(24).fill(0), Other: new Array(24).fill(0) };
    data.forEach(d => {
        const parts = (d.timestamp || "").split(" ");
        const hour = parts[1] ? parseInt(parts[1].split(":")[0]) : -1;
        if (hour < 0) return;
        const school = (d.school || "");
        if (school.includes("Engineering")) hourBins.SOE[hour]++;
        else if (school.includes("Business")) hourBins.SOB[hour]++;
        else hourBins.Other[hour]++;
    });

    // Only keep hours that have at least 1 JD
    const activeHours = [];
    for (let h = 0; h < 24; h++) {
        if (hourBins.SOE[h] + hourBins.SOB[h] + hourBins.Other[h] > 0) activeHours.push(h);
    }
    const labels = activeHours.map(h => `${h.toString().padStart(2,"0")}:00`);

    const ctx = canvas.getContext("2d");
    chartInstances.timeline = new Chart(ctx, {
        type: "bar",
        data: {
            labels: labels.length ? labels : ["No data"],
            datasets: [
                {
                    label: "SOE – Engineering",
                    data: activeHours.map(h => hourBins.SOE[h]),
                    backgroundColor: "rgba(99,102,241,0.82)",
                    hoverBackgroundColor: "rgba(99,102,241,1)",
                    borderRadius: 6,
                    borderSkipped: false,
                },
                {
                    label: "SOB – Business",
                    data: activeHours.map(h => hourBins.SOB[h]),
                    backgroundColor: "rgba(245,158,11,0.82)",
                    hoverBackgroundColor: "rgba(245,158,11,1)",
                    borderRadius: 6,
                    borderSkipped: false,
                },
                {
                    label: "Other / Unclassified",
                    data: activeHours.map(h => hourBins.Other[h]),
                    backgroundColor: "rgba(100,116,139,0.55)",
                    hoverBackgroundColor: "rgba(100,116,139,0.8)",
                    borderRadius: 6,
                    borderSkipped: false,
                },
            ],
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            interaction: { mode: "index", intersect: false },
            plugins: {
                legend: {
                    position: "top",
                    align: "end",
                    labels: {
                        usePointStyle: true,
                        pointStyle: "rectRounded",
                        boxWidth: 10,
                        boxHeight: 10,
                        padding: 16,
                        font: { family: "'Inter', sans-serif", size: 11, weight: "600" },
                        color: "#4b5563",
                    },
                },
                subtitle: {
                    display: true,
                    text: `JDs received by hour of day — ${dateLabel || "Today"} · Colour = School`,
                    color: "#6b7280",
                    font: { family: "'Inter', sans-serif", size: 11 },
                    padding: { bottom: 8 },
                    align: "start",
                },
                tooltip: {
                    backgroundColor: "rgba(15,23,42,0.93)",
                    titleColor: "#f1f5f9",
                    titleFont: { family: "'Outfit', sans-serif", size: 13, weight: "700" },
                    bodyColor: "#94a3b8",
                    bodyFont: { family: "'Inter', sans-serif", size: 11 },
                    padding: 14,
                    cornerRadius: 12,
                    borderWidth: 1,
                    borderColor: "rgba(99,102,241,0.3)",
                    callbacks: {
                        title: items => `🕐 ${items[0].label}  ·  ${dateLabel || ""}`,
                        label: item => ` ${item.dataset.label}: ${item.parsed.y} JD${item.parsed.y !== 1 ? "s" : ""}`,
                        afterBody: items => {
                            const total = items.reduce((s, i) => s + i.parsed.y, 0);
                            return total > 0 ? [``, ` Total this hour: ${total} JDs`] : [];
                        },
                    },
                },
            },
            scales: {
                x: {
                    grid: { display: false },
                    ticks: { color: "#6b7280", font: { size: 11 } },
                    title: {
                        display: true,
                        text: "Hour of Day (IST)",
                        color: "#6b7280",
                        font: { size: 11, family: "'Inter', sans-serif" },
                    },
                },
                y: {
                    beginAtZero: true,
                    ticks: { stepSize: 1, color: "#9ca3af", font: { size: 11 } },
                    grid: { color: "rgba(0,0,0,0.04)" },
                    title: {
                        display: true,
                        text: "JDs Received",
                        color: "#6b7280",
                        font: { size: 11, family: "'Inter', sans-serif" },
                    },
                },
            },
        },
    });
}

// ── Multi-day view: stacked bars by school + cumulative line ─────
function _renderMultiDayTimeline(canvas, data) {
    // Group by date × school
    const daySOE = {}, daySOB = {}, dayOther = {};
    data.forEach(d => {
        const day = formatDate(d.timestamp);
        if (!day) return;
        const school = d.school || "";
        if (school.includes("Engineering")) daySOE[day] = (daySOE[day] || 0) + 1;
        else if (school.includes("Business")) daySOB[day]  = (daySOB[day]  || 0) + 1;
        else dayOther[day] = (dayOther[day] || 0) + 1;
    });

    const allDays = [...new Set([...Object.keys(daySOE), ...Object.keys(daySOB), ...Object.keys(dayOther)])].sort();
    const soeVals   = allDays.map(d => daySOE[d]   || 0);
    const sobVals   = allDays.map(d => daySOB[d]   || 0);
    const otherVals = allDays.map(d => dayOther[d] || 0);

    // Cumulative total
    let cum = 0;
    const cumVals = allDays.map((_, i) => {
        cum += soeVals[i] + sobVals[i] + otherVals[i];
        return cum;
    });

    const ctx = canvas.getContext("2d");

    // Gradient for cumulative line
    const gradH = canvas.height || 200;
    const grad = ctx.createLinearGradient(0, 0, 0, gradH);
    grad.addColorStop(0, "rgba(16,185,129,0.25)");
    grad.addColorStop(1, "rgba(16,185,129,0)");

    chartInstances.timeline = new Chart(ctx, {
        data: {
            labels: allDays,
            datasets: [
                {
                    type: "bar",
                    label: "SOE – Engineering",
                    data: soeVals,
                    backgroundColor: "rgba(99,102,241,0.82)",
                    hoverBackgroundColor: "rgba(99,102,241,1)",
                    borderRadius: { topLeft: 4, topRight: 4 },
                    borderSkipped: false,
                    stack: "daily",
                    order: 2,
                },
                {
                    type: "bar",
                    label: "SOB – Business",
                    data: sobVals,
                    backgroundColor: "rgba(245,158,11,0.82)",
                    hoverBackgroundColor: "rgba(245,158,11,1)",
                    borderRadius: { topLeft: 4, topRight: 4 },
                    borderSkipped: false,
                    stack: "daily",
                    order: 2,
                },
                {
                    type: "bar",
                    label: "Other",
                    data: otherVals,
                    backgroundColor: "rgba(100,116,139,0.55)",
                    hoverBackgroundColor: "rgba(100,116,139,0.8)",
                    borderRadius: { topLeft: 4, topRight: 4 },
                    borderSkipped: false,
                    stack: "daily",
                    order: 2,
                },
                {
                    type: "line",
                    label: "Cumulative Total",
                    data: cumVals,
                    borderColor: "rgba(16,185,129,0.9)",
                    backgroundColor: grad,
                    fill: true,
                    tension: 0.4,
                    pointRadius: 4,
                    pointHoverRadius: 7,
                    pointBackgroundColor: "rgba(16,185,129,1)",
                    pointBorderColor: "#fff",
                    pointBorderWidth: 2,
                    borderWidth: 2.5,
                    yAxisID: "yCum",
                    order: 1,
                },
            ],
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            interaction: { mode: "index", intersect: false },
            plugins: {
                legend: {
                    position: "top",
                    align: "end",
                    labels: {
                        usePointStyle: true,
                        pointStyle: "circle",
                        boxWidth: 8,
                        boxHeight: 8,
                        padding: 14,
                        font: { family: "'Inter', sans-serif", size: 11, weight: "600" },
                        color: "#4b5563",
                    },
                },
                subtitle: {
                    display: true,
                    text: "Daily JDs by school (bars) · Cumulative total (green line, right axis)",
                    color: "#6b7280",
                    font: { family: "'Inter', sans-serif", size: 11 },
                    padding: { bottom: 8 },
                    align: "start",
                },
                tooltip: {
                    backgroundColor: "rgba(15,23,42,0.93)",
                    titleColor: "#f1f5f9",
                    titleFont: { family: "'Outfit', sans-serif", size: 13, weight: "700" },
                    bodyColor: "#94a3b8",
                    bodyFont: { family: "'Inter', sans-serif", size: 11 },
                    padding: 14,
                    cornerRadius: 12,
                    borderWidth: 1,
                    borderColor: "rgba(99,102,241,0.3)",
                    callbacks: {
                        title: items => `📅 ${items[0].label}`,
                        label: item => ` ${item.dataset.label}: ${item.parsed.y}`,
                    },
                },
            },
            scales: {
                x: {
                    grid: { display: false },
                    ticks: { color: "#6b7280", font: { size: 11 } },
                    title: {
                        display: true,
                        text: "Date",
                        color: "#6b7280",
                        font: { size: 11, family: "'Inter', sans-serif" },
                    },
                },
                y: {
                    stacked: true,
                    beginAtZero: true,
                    ticks: { stepSize: 1, color: "#9ca3af", font: { size: 11 } },
                    grid: { color: "rgba(0,0,0,0.04)" },
                    title: {
                        display: true,
                        text: "JDs per Day",
                        color: "#6b7280",
                        font: { size: 11, family: "'Inter', sans-serif" },
                    },
                },
                yCum: {
                    type: "linear",
                    position: "right",
                    beginAtZero: true,
                    ticks: { color: "rgba(16,185,129,0.8)", font: { size: 11 } },
                    grid: { display: false },
                    title: {
                        display: true,
                        text: "Cumulative Total",
                        color: "rgba(16,185,129,0.7)",
                        font: { size: 11, family: "'Inter', sans-serif" },
                    },
                },
            },
        },
    });
}



// ── Chart: Company Distribution (horizontal bar) ─────────────
function renderCompanyChart(data) {
    const map = countBy(data, "company");
    const sorted = Object.entries(map)
        .sort((a, b) => b[1] - a[1])
        .slice(0, 10);                       // ← top 10 only

    const labels = sorted.map(([k]) => k.length > 26 ? k.slice(0, 24) + "…" : k);
    const values = sorted.map(([, v]) => v);
    const maxVal = Math.max(...values, 1);

    // Use multiple professional colors from the palette for each bar
    const bgColors = sorted.map((_, idx) => COLORS.palette[idx % COLORS.palette.length]);
    const borderColors = sorted.map((_, idx) => {
        const baseColor = COLORS.palette[idx % COLORS.palette.length];
        return baseColor.replace("0.85", "1");
    });
    const hoverColors = sorted.map((_, idx) => {
        const baseColor = COLORS.palette[idx % COLORS.palette.length];
        return baseColor.replace("0.85", "0.95");
    });

    const canvas = document.getElementById("companyChart");
    if (!canvas) return;
    const existingChart = Chart.getChart(canvas);
    if (existingChart) existingChart.destroy();

    const ctx = canvas.getContext("2d");
    chartInstances.company = new Chart(ctx, {
        type: "bar",
        data: {
            labels,
            datasets: [{
                label: "JD Count",
                data: values,
                backgroundColor: bgColors,
                borderColor: borderColors,
                hoverBackgroundColor: hoverColors,
                borderWidth: 1,
                borderRadius: 6,
                borderSkipped: false,
                barThickness: 20,
            }],
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            indexAxis: "y",
            layout: { padding: { right: 40 } },
            plugins: {
                legend: { display: false },
                subtitle: {
                    display: true,
                    text: "Number of job descriptions received per company (Top 10)",
                    color: "#6b7280",
                    font: { family: "'Inter', sans-serif", size: 11, style: "normal" },
                    padding: { bottom: 10 },
                    align: "start",
                },
                tooltip: {
                    backgroundColor: "rgba(15,23,42,0.92)",
                    titleColor: "#e2e8f0",
                    titleFont: { family: "'Outfit', sans-serif", size: 13, weight: "700" },
                    bodyColor: "#94a3b8",
                    bodyFont: { family: "'Inter', sans-serif", size: 11 },
                    padding: 12,
                    cornerRadius: 10,
                    displayColors: false,
                    borderWidth: 1,
                    borderColor: "rgba(99,102,241,0.25)",
                    callbacks: {
                        title: items => items[0].label,
                        label: item => ` ${item.parsed.x} JD${item.parsed.x !== 1 ? "s" : ""} received`,
                    },
                },
                // Inline data labels on each bar
                datalabels: false,
            },
            scales: {
                x: {
                    beginAtZero: true,
                    ticks: {
                        stepSize: 1,
                        color: "#9ca3af",
                        font: { size: 11 },
                    },
                    grid: { color: "rgba(0,0,0,0.05)", drawBorder: false },
                    title: {
                        display: true,
                        text: "Number of JDs",
                        color: "#6b7280",
                        font: { size: 11, family: "'Inter', sans-serif" },
                        padding: { top: 6 },
                    },
                },
                y: {
                    grid: { display: false },
                    ticks: {
                        color: "#374151",
                        font: { size: 11, family: "'Inter', sans-serif", weight: "500" },
                    },
                },
            },
            // Draw value labels at end of each bar
            animation: {
                onComplete(anim) {
                    const chart = anim.chart;
                    const c = chart.ctx;
                    c.save();
                    c.font = "bold 11px 'Inter', sans-serif";
                    c.fillStyle = "#374151";
                    c.textAlign = "left";
                    c.textBaseline = "middle";
                    chart.data.datasets[0].data.forEach((val, i) => {
                        const meta = chart.getDatasetMeta(0);
                        const bar = meta.data[i];
                        if (bar) {
                            c.fillText(` ${val} JD${val !== 1 ? "s" : ""}`, bar.x + 4, bar.y);
                        }
                    });
                    c.restore();
                },
            },
        },
    });
}


// ── Chart: Seniority Breakdown (doughnut) ────────────────────
function renderSeniorityChart(data) {
    const map = countBy(data, "seniority");
    const labels = Object.keys(map);
    const values = Object.values(map);

    const canvas = document.getElementById("seniorityChart");
    if (!canvas) return;
    const existingChart = Chart.getChart(canvas);
    if (existingChart) existingChart.destroy();

    const ctx = canvas.getContext("2d");
    chartInstances.seniority = new Chart(ctx, {
        type: "doughnut",
        data: {
            labels,
            datasets: [{
                data: values,
                backgroundColor: COLORS.palette.slice(0, labels.length),
                borderColor: "#fff",
                borderWidth: 3,
                hoverOffset: 8,
            }],
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            cutout: "62%",
            plugins: {
                legend: {
                    position: "bottom",
                    labels: {
                        usePointStyle: true,
                        pointStyle: "circle",
                        boxWidth: 8,
                        boxHeight: 8,
                        padding: 12,
                        font: {
                            family: "'Inter', sans-serif",
                            size: 10,
                            weight: "600"
                        },
                        color: "#4b5563"
                    }
                },
                tooltip: {
                    backgroundColor: "rgba(30, 27, 75, 0.95)",
                    titleColor: "#ffffff",
                    titleFont: { family: "'Outfit', sans-serif", size: 12, weight: "700" },
                    bodyColor: "#c7d2fe",
                    bodyFont: { family: "'Inter', sans-serif", size: 11, weight: "500" },
                    padding: 10,
                    cornerRadius: 8,
                    displayColors: true,
                    boxWidth: 6,
                    boxHeight: 6,
                    boxPadding: 4,
                    borderWidth: 1,
                    borderColor: "rgba(99, 102, 241, 0.15)",
                    callbacks: {
                        label: ctx => ` Count: ${ctx.parsed} (${((ctx.parsed / data.length) * 100).toFixed(0)}%)`,
                    }
                },
            },
        },
    });
}

// ── Chart: School Distribution (doughnut) ───────────────────
function renderSchoolChart(data) {
    const canvas = document.getElementById("schoolChart");
    if (!canvas) return;

    const map = countBy(data, "school");
    const labels = Object.keys(map);
    const values = Object.values(map);

    const existingChart = Chart.getChart(canvas);
    if (existingChart) existingChart.destroy();

    const SCHOOL_COLORS = {
        "School of Engineering (SOE)": "rgba(37, 99, 235, 1)",   // Solid tech blue
        "School of Business (SOB)":    "rgba(217, 119, 6, 1)",    // Solid warm amber
        "School of Science (SOS)":     "rgba(5, 150, 105, 1)",    // Solid deep emerald
        "School of Humanity (SOH)":    "rgba(219, 39, 119, 1)",   // Solid rose pink
        "School of Law (SOL)":         "rgba(124, 58, 237, 1)",   // Solid royal purple
    };
    const bgColors = labels.map(label => SCHOOL_COLORS[label] || "rgba(99,102,241,1)");

    const ctx = canvas.getContext("2d");
    chartInstances.school = new Chart(ctx, {
        type: "doughnut",
        data: {
            labels,
            datasets: [{
                data: values,
                backgroundColor: bgColors,
                borderColor: "#fff",
                borderWidth: 3,
                hoverOffset: 8,
            }],
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            cutout: "60%",
            plugins: {
                legend: {
                    position: "bottom",
                    labels: {
                        usePointStyle: true,
                        pointStyle: "circle",
                        boxWidth: 8,
                        boxHeight: 8,
                        padding: 12,
                        font: {
                            family: "'Inter', sans-serif",
                            size: 10,
                            weight: "600"
                        },
                        color: "#4b5563"
                    }
                },
                tooltip: {
                    backgroundColor: "rgba(30, 27, 75, 0.95)",
                    titleColor: "#ffffff",
                    titleFont: { family: "'Outfit', sans-serif", size: 12, weight: "700" },
                    bodyColor: "#c7d2fe",
                    bodyFont: { family: "'Inter', sans-serif", size: 11, weight: "500" },
                    padding: 10,
                    cornerRadius: 8,
                    displayColors: true,
                    boxWidth: 6,
                    boxHeight: 6,
                    boxPadding: 4,
                    borderWidth: 1,
                    borderColor: "rgba(99, 102, 241, 0.15)",
                    callbacks: {
                        label: ctx => ` Count: ${ctx.parsed} (${((ctx.parsed / data.length) * 100).toFixed(0)}%)`,
                    }
                },
            },
        },
    });
}

// ── Chart: Role Distribution (polar area) ────────────────────
function renderRoleChart(data) {
    const map = countBy(data, "role");
    const sorted = Object.entries(map).sort((a, b) => b[1] - a[1]).slice(0, 8);
    const fullLabels = sorted.map(s => s[0]);
    const labels = sorted.map(s => s[0].length > 20 ? s[0].slice(0, 18) + "…" : s[0]);
    const values = sorted.map(s => s[1]);

    const canvas = document.getElementById("roleChart");
    if (!canvas) return;
    const existingChart = Chart.getChart(canvas);
    if (existingChart) existingChart.destroy();

    const ctx = canvas.getContext("2d");
    chartInstances.role = new Chart(ctx, {
        type: "polarArea",
        data: {
            labels,
            datasets: [{
                data: values,
                backgroundColor: COLORS.palette.slice(0, labels.length),
                borderColor: "#ffffff",
                borderWidth: 3,
                hoverBorderWidth: 3,
                hoverBorderColor: "#ffffff",
                hoverOffset: 15,
            }],
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                legend: {
                    position: "bottom",
                    labels: {
                        usePointStyle: true,
                        pointStyle: "circle",
                        boxWidth: 8,
                        boxHeight: 8,
                        padding: 12,
                        font: {
                            family: "'Inter', sans-serif",
                            size: 10,
                            weight: "600"
                        },
                        color: "#4b5563"
                    }
                },
                tooltip: {
                    backgroundColor: "rgba(30, 27, 75, 0.95)",
                    titleColor: "#ffffff",
                    titleFont: { family: "'Outfit', sans-serif", size: 12, weight: "700" },
                    bodyColor: "#c7d2fe",
                    bodyFont: { family: "'Inter', sans-serif", size: 11, weight: "500" },
                    padding: 10,
                    cornerRadius: 8,
                    displayColors: true,
                    boxWidth: 6,
                    boxHeight: 6,
                    boxPadding: 4,
                    borderWidth: 1,
                    borderColor: "rgba(99, 102, 241, 0.15)",
                    callbacks: {
                        title: context => {
                            const index = context[0].dataIndex;
                            return fullLabels[index] || "";
                        },
                        label: context => {
                            const val = context.raw;
                            return ` Count: ${val} application${val !== 1 ? "s" : ""} (${((val / data.length) * 100).toFixed(0)}%)`;
                        }
                    }
                },
            },
            scales: {
                r: {
                    grid: {
                        color: "rgba(99, 102, 241, 0.04)",
                        circular: true
                    },
                    angleLines: {
                        color: "rgba(99, 102, 241, 0.04)",
                        lineWidth: 1
                    },
                    ticks: {
                        display: false,
                        backdropColor: "transparent"
                    },
                    pointLabels: {
                        display: false
                    }
                }
            },
        },
    });
}

// ── Chart: CTC Distribution (bar) ────────────────────────────
function renderCtcChart(data) {
    const ctcCanvas = document.getElementById("ctcChart");
    if (!ctcCanvas) return;

    const ctcData = data
        .filter(d => d.ctc && d.ctc.trim())
        .map(d => {
            const raw = (d.ctc || "").trim();
            let ctcLPA = 0;

            const hasLPA = /lpa|l\.p\.a|per\s*annum/i.test(raw);
            const nums = raw.match(/[\d.]+/g)?.map(Number).filter(n => !isNaN(n)) || [];

            if (nums.length === 0) return { company: d.company, ctc: raw, ctcLPA: 0 };

            if (hasLPA && raw.includes("-")) {
                // LPA range: "3.60 - 4.20 LPA"
                const validNums = nums.filter(n => n > 0);
                if (validNums.length >= 2) {
                    const avg = (validNums[0] + validNums[1]) / 2;
                    ctcLPA = avg > 100 ? avg / 100000 : avg; // "1323200LPA" safeguard
                } else {
                    ctcLPA = validNums[0] > 100 ? validNums[0] / 100000 : validNums[0];
                }
            } else if (hasLPA) {
                // Single LPA value: "11.10 LPA" or "1323200LPA"
                const val = nums[0];
                ctcLPA = val > 100 ? val / 100000 : val;
            } else if (raw.includes("-")) {
                // INR range: "INR 400000-675000" or "INR 618000 - 702000"
                const validNums = nums.filter(n => n > 0);
                if (validNums.length >= 2) {
                    ctcLPA = (validNums[validNums.length - 2] + validNums[validNums.length - 1]) / 2 / 100000;
                } else if (validNums.length === 1) {
                    ctcLPA = validNums[0] / 100000;
                }
            } else {
                // Raw number: "500000", "INR 468000", "405233"
                const num = nums[0];
                ctcLPA = num > 100 ? num / 100000 : num;
            }

            // Filter out very small values (likely monthly stipends, e.g., INR 20000 = 0.2 LPA)
            if (ctcLPA < 0.5) ctcLPA = 0;

            return { company: d.company, ctc: raw, ctcLPA: Math.round(ctcLPA * 100) / 100 };
        })
        .filter(d => d.ctcLPA > 0)
        .sort((a, b) => b.ctcLPA - a.ctcLPA)
        .slice(0, 10);

    if (ctcData.length === 0) return;

    const existingChart = Chart.getChart(ctcCanvas);
    if (existingChart) existingChart.destroy();

    const ctx = ctcCanvas.getContext("2d");
    chartInstances.ctc = new Chart(ctx, {
        type: "bar",
        data: {
            labels: ctcData.map(d => d.company.length > 18 ? d.company.slice(0, 16) + "…" : d.company),
            datasets: [{
                label: "CTC (LPA)",
                data: ctcData.map(d => d.ctcLPA),
                backgroundColor: COLORS.palette.slice(0, ctcData.length),
                borderRadius: 6,
                borderSkipped: false,
            }],
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                legend: { display: false },
                tooltip: {
                    backgroundColor: "rgba(30, 27, 75, 0.95)",
                    titleColor: "#ffffff",
                    titleFont: { family: "'Outfit', sans-serif", size: 12, weight: "700" },
                    bodyColor: "#c7d2fe",
                    bodyFont: { family: "'Inter', sans-serif", size: 11, weight: "500" },
                    padding: 10,
                    cornerRadius: 8,
                    displayColors: false,
                    borderWidth: 1,
                    borderColor: "rgba(99, 102, 241, 0.15)",
                    callbacks: {
                        title: context => {
                            const index = context[0].dataIndex;
                            return ctcData[index].company || "";
                        },
                        label: context => {
                            const index = context.dataIndex;
                            return ` CTC: ${ctcData[index].ctc}`;
                        }
                    }
                },
            },
            scales: {
                y: { beginAtZero: true, grid: { color: "rgba(14,36,48,0.04)" }, title: { display: true, text: "LPA", font: { size: 11, weight: "600" } } },
                x: { grid: { display: false } },
            },
        },
    });
}

// ── Chart: Skills Cloud (horizontal bar) ─────────────────────
function renderSkillsChart(data) {
    const skillsCanvas = document.getElementById("skillsChart");
    if (!skillsCanvas) return;

    const skillMap = {};
    data.forEach(d => {
        if (!d.skills) return;
        d.skills.split(/[,;|]/).forEach(s => {
            const skill = s.trim();
            if (skill && skill.length > 1) {
                const lowerSkill = skill.toLowerCase();
                if (!skillMap[lowerSkill]) {
                    skillMap[lowerSkill] = { count: 0, cases: {} };
                }
                skillMap[lowerSkill].count += 1;
                skillMap[lowerSkill].cases[skill] = (skillMap[lowerSkill].cases[skill] || 0) + 1;
            }
        });
    });

    const resolvedSkillMap = {};
    Object.entries(skillMap).forEach(([lowerSkill, info]) => {
        let bestCase = "";
        let maxCount = -1;
        Object.entries(info.cases).forEach(([casing, count]) => {
            if (count > maxCount) {
                maxCount = count;
                bestCase = casing;
            }
        });
        resolvedSkillMap[bestCase] = info.count;
    });

    const sorted = Object.entries(resolvedSkillMap).sort((a, b) => b[1] - a[1]).slice(0, 12);
    if (sorted.length === 0) return;

    const existingChart = Chart.getChart(skillsCanvas);
    if (existingChart) existingChart.destroy();

    const ctx = skillsCanvas.getContext("2d");
    chartInstances.skills = new Chart(ctx, {
        type: "bar",
        data: {
            labels: sorted.map(s => s[0].length > 22 ? s[0].slice(0, 20) + "…" : s[0]),
            datasets: [{
                label: "Frequency",
                data: sorted.map(s => s[1]),
                backgroundColor: COLORS.paletteSoft.slice(0, sorted.length),
                borderColor: COLORS.palette.slice(0, sorted.length),
                borderWidth: 1.5,
                borderRadius: 4,
                barThickness: 18,
            }],
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            indexAxis: "y",
            plugins: {
                legend: { display: false },
                tooltip: {
                    backgroundColor: "rgba(30, 27, 75, 0.95)",
                    titleColor: "#ffffff",
                    titleFont: { family: "'Outfit', sans-serif", size: 12, weight: "700" },
                    bodyColor: "#c7d2fe",
                    bodyFont: { family: "'Inter', sans-serif", size: 11, weight: "500" },
                    padding: 10,
                    cornerRadius: 8,
                    displayColors: false,
                    borderWidth: 1,
                    borderColor: "rgba(99, 102, 241, 0.15)",
                    callbacks: {
                        label: ctx => ` Demanded in: ${ctx.parsed.x} JD${ctx.parsed.x !== 1 ? "s" : ""}`,
                    }
                },
            },
            scales: {
                x: { beginAtZero: true, ticks: { stepSize: 1 }, grid: { color: "rgba(14,36,48,0.04)" } },
                y: { grid: { display: false } },
            },
        },
    });
}

// ── Data Table ───────────────────────────────────────────────
let currentSort = { key: "timestamp", asc: true };

function renderTable(data) {
    const tbody = document.getElementById("dashTableBody");
    if (!data || data.length === 0) {
        tbody.innerHTML = `
        <tr>
          <td colspan="8" style="text-align:center; padding: 3rem 1rem; color: var(--text-muted, #6b7280);">
            <div style="display:flex;flex-direction:column;align-items:center;gap:0.75rem;">
              <span class="material-symbols-rounded" style="font-size:3rem;opacity:0.35;">inbox</span>
              <strong style="font-size:1rem;">No JD data found</strong>
              <span style="font-size:0.85rem;">The Google Sheet is empty. Analyse a JD to populate the dashboard.</span>
            </div>
          </td>
        </tr>`;
        document.getElementById("tableResultCount").textContent = "0 results";
        return;
    }
    const rows = data.map(d => `
    <tr>
      <td>${formatDateTime(d.timestamp)}</td>
      <td><strong>${d.company}</strong></td>
      <td><span class="cycle-badge">${d.cycle}</span></td>
      <td>${d.role}</td>
      <td><span class="seniority-badge ${(d.seniority || 'unknown').toLowerCase().replace(/[\s-]/g, '_')}">${d.seniority || "—"}</span></td>
      <td>${renderSchoolBadges(d.school, d.eligibility, d.role)}</td>
      <td>${d.location || "—"}</td>
      <td>${d.ctc || "—"}</td>
    </tr>
  `).join("");
    tbody.innerHTML = rows;
    document.getElementById("tableResultCount").textContent = `${data.length} result${data.length !== 1 ? "s" : ""}`;
}

function sortData(data, key, asc) {
    return [...data].sort((a, b) => {
        const va = (a[key] || "").toLowerCase();
        const vb = (b[key] || "").toLowerCase();
        return asc ? va.localeCompare(vb) : vb.localeCompare(va);
    });
}

function getFilteredData() {
    const query = (document.getElementById("dashSearch").value || "").toLowerCase();
    const senFilter = document.getElementById("seniorityFilter").value;
    const schoolFilter = document.getElementById("schoolFilter") ? document.getElementById("schoolFilter").value : "";
    let filtered = SHEET_DATA;
    if (query) {
        filtered = filtered.filter(d =>
            d.company.toLowerCase().includes(query) ||
            d.role.toLowerCase().includes(query) ||
            (d.seniority || "").toLowerCase().includes(query) ||
            (d.location || "").toLowerCase().includes(query) ||
            (d.ctc || "").toLowerCase().includes(query) ||
            (d.school || "").toLowerCase().includes(query)
        );
    }
    if (senFilter) {
        filtered = filtered.filter(d => (d.seniority || "Unknown") === senFilter);
    }
    if (schoolFilter) {
        filtered = filtered.filter(d => {
            if ((d.school || "Unknown") === schoolFilter) return true;
            const textToScan = `${d.eligibility || ""} ${d.role || ""}`;
            const courses = extractCoursesHeuristically(textToScan);
            for (const course of courses) {
                if (classifyCourseToSchool(course) === schoolFilter) return true;
            }
            return false;
        });
    }
    return sortData(filtered, currentSort.key, currentSort.asc);
}

// ── Seniority Filter Dropdown ────────────────────────────────
function populateSeniorityFilter(data) {
    const sel = document.getElementById("seniorityFilter");
    if (!sel) return;
    // Clear existing options except the first "All" option
    while (sel.options.length > 1) sel.remove(1);
    const unique = uniqueValues(data, "seniority");
    unique.sort().forEach(s => {
        const opt = document.createElement("option");
        opt.value = s;
        opt.textContent = s;
        sel.appendChild(opt);
    });
}

// ── School Filter Dropdown ───────────────────────────────────
function populateSchoolFilter(data) {
    const sel = document.getElementById("schoolFilter");
    if (!sel) return;
    // Clear existing options except the first "All" option
    while (sel.options.length > 1) sel.remove(1);
    const unique = uniqueValues(data, "school");
    
    const primarySchools = [
        "School of Engineering (SOE)",
        "School of Business (SOB)",
        "School of Science (SOS)",
        "School of Humanity (SOH)",
        "School of Law (SOL)"
    ];
    
    const allSchools = [...new Set([...primarySchools, ...unique])].filter(Boolean);
    allSchools.sort().forEach(s => {
        // Avoid duplicates if pre-populated in HTML
        if (![...sel.options].some(o => o.value === s)) {
            const opt = document.createElement("option");
            opt.value = s;
            opt.textContent = s;
            sel.appendChild(opt);
        }
    });
}

// ── School Pill Filter Logic ─────────────────────────────────

let activeSchoolFilter = "";

function initSchoolPillListeners() {
    const pills = document.querySelectorAll(".school-pill");
    pills.forEach(pill => {
        pill.addEventListener("click", () => {
            const school = pill.dataset.school;
            activeSchoolFilter = school;

            // Update hidden select for getFilteredData compatibility
            const sel = document.getElementById("schoolFilter");
            if (sel) sel.value = school;

            // Update pill active state
            pills.forEach(p => p.classList.toggle("active", p.dataset.school === school));

            // Update charts + table
            applySchoolFilter(school);

            // Show or hide the spotlight panel
            if (school) {
                showSchoolSpotlight(school);
            } else {
                hideSchoolSpotlight();
            }
        });
    });

    // Close button inside spotlight panel
    document.getElementById("closeSpotlight")?.addEventListener("click", () => {
        activeSchoolFilter = "";
        const sel = document.getElementById("schoolFilter");
        if (sel) sel.value = "";
        pills.forEach(p => p.classList.toggle("active", p.dataset.school === ""));
        applySchoolFilter("");
        hideSchoolSpotlight();
    });
}

function applySchoolFilter(school) {
    const filtered = getFilteredData();

    // ── Re-render everything with filtered data ───────────────
    // Destroy all charts so they redraw cleanly
    destroyCharts();

    // KPI cards with filtered data
    renderKPIs(filtered);

    // All charts with filtered data
    renderTimelineChart(filtered);
    renderCompanyChart(filtered);
    renderSeniorityChart(filtered);
    renderRoleChart(filtered);
    renderCtcChart(filtered);
    renderSkillsChart(filtered);

    // School chart: always full data (shows distribution context),
    // but highlight the selected school visually
    renderSchoolChartHighlighted(SHEET_DATA, school);

    // Table
    renderTable(filtered);

    // Banner + count
    updateSchoolContextBanner(school, filtered);
    updateFilteredCount(school, filtered);

    // Visual pulse on chart grid to signal redraw
    const grid = document.querySelector('.chart-grid');
    if (grid) {
        grid.classList.add('school-filter-pulse');
        setTimeout(() => grid.classList.remove('school-filter-pulse'), 600);
    }

    // If clearing filter, restore full dashboard
    if (!school) {
        renderDashboardCharts(SHEET_DATA);
    }
}

// Full charts re-render helper (used for both initial load and filter reset)
function renderDashboardCharts(data) {
    destroyCharts();
    renderKPIs(data);
    renderTimelineChart(data);
    renderCompanyChart(data);
    renderSeniorityChart(data);
    renderSchoolChart(data);
    renderRoleChart(data);
    renderCtcChart(data);
    renderSkillsChart(data);
}

// ── School Spotlight Panel ────────────────────────────────────
const SCHOOL_META = {
    "School of Engineering (SOE)": {
        theme: "soe-theme",
        icon: "engineering",
        color: "#3b82f6",
        abbr:  "SOE",
        accent: "rgba(59,130,246,",
        desc: "Technical & Engineering roles — Software, Data, DevOps, AI"
    },
    "School of Business (SOB)": {
        theme: "sob-theme",
        icon: "apartment",
        color: "#f59e0b",
        abbr:  "SOB",
        accent: "rgba(245,158,11,",
        desc: "Business, Management & Commerce roles — MBA, Finance, Marketing"
    }
};

// Track spotlight chart instances separately
const spCharts = {};
function destroySpotlightCharts() {
    Object.values(spCharts).forEach(c => { try { c.destroy(); } catch(e){} });
    Object.keys(spCharts).forEach(k => delete spCharts[k]);
}

function showSchoolSpotlight(school) {
    const panel    = document.getElementById("schoolSpotlight");
    const meta     = SCHOOL_META[school] || { theme:"soe-theme", icon:"school", color:"#6366f1", accent:"rgba(99,102,241,", desc:"" };
    const filtered = SHEET_DATA.filter(d => (d.school || "") === school);

    if (!panel) return;

    // Apply theme colour
    panel.className = `school-spotlight ${meta.theme}`;

    // Update header
    document.getElementById("spotlightIcon").textContent = meta.icon;
    document.getElementById("spotlightName").textContent = school;
    document.getElementById("spotlightSubtitle").textContent = meta.desc;

    // KPIs
    const companies   = new Set(filtered.map(d => d.company).filter(Boolean));
    const roles       = new Set(filtered.map(d => d.role).filter(Boolean));
    const senMap      = countBy(filtered, "seniority");
    const topSen      = Object.entries(senMap).sort((a,b) => b[1]-a[1])[0]?.[0] || "—";
    const share       = SHEET_DATA.length ? Math.round(filtered.length / SHEET_DATA.length * 100) : 0;

    // ── Smart CTC parser — handles INR raw, LPA, monthly, ranges ──
    function parseCTCtoLPA(raw) {
        if (!raw) return null;
        const s = raw.replace(/,/g, ""); // remove commas from "4,82,020"

        // Extract all numbers from the string
        const nums = [...s.matchAll(/[\d]+(?:\.\d+)?/g)].map(m => parseFloat(m[0]));
        if (!nums.length) return null;

        // Pick the first meaningful number (skip tiny ones like "6.5" prefix from "6.5 LPA" contexts)
        let val = nums[0];

        // If string says "per month" / "monthly" → annualise × 12
        const isMonthly = /per\s*month|monthly|p\.?m\.?/i.test(s);
        if (isMonthly) val = val * 12;

        // Decide unit: if value >= 10000 it's in ₹ → convert to LPA (÷ 100000)
        // if < 1000 it's already LPA; values 1000–9999 are ambiguous — skip
        if (val >= 10000) {
            val = val / 100000; // ₹ → LPA
        } else if (val >= 1000) {
            return null; // ambiguous — skip
        }
        // Sanity bounds: CTC should be 0.5–200 LPA
        if (val < 0.5 || val > 200) return null;
        return val;
    }

    const ctcNums = filtered.map(d => parseCTCtoLPA(d.ctc)).filter(n => n !== null);
    const avgCtcVal = ctcNums.length
        ? ctcNums.reduce((a, b) => a + b, 0) / ctcNums.length
        : null;
    const avgCtc = avgCtcVal !== null
        ? avgCtcVal.toFixed(1) + " LPA"
        : "—";


    // ── Highest Package ────────────────────────────────────────
    const highestCtc = ctcNums.length ? Math.max(...ctcNums).toFixed(1) + " LPA" : "—";

    document.getElementById("spTotal").textContent        = filtered.length;
    document.getElementById("spCompanies").textContent    = companies.size;
    document.getElementById("spRoles").textContent        = roles.size;
    document.getElementById("spAvgCtc").textContent       = avgCtc;
    document.getElementById("spHighestCtc").textContent   = highestCtc;
    document.getElementById("spTopSeniority").textContent = topSen;
    document.getElementById("spShare").textContent        = share + "%";

    // Render 5 spotlight charts
    destroySpotlightCharts();
    renderSpotlightCharts(filtered, meta);

    // Show with animation
    panel.classList.remove("hidden");
    panel.scrollIntoView({ behavior: "smooth", block: "nearest" });
}

function hideSchoolSpotlight() {
    const panel = document.getElementById("schoolSpotlight");
    if (panel) panel.classList.add("hidden");
    destroySpotlightCharts();
}

function renderSpotlightCharts(data, meta) {
    const accent = meta.accent;

    // ── Top Roles ──────────────────────────────────────────────
    const roleMap = countBy(data, "role");
    const roleTop = Object.entries(roleMap).sort((a,b)=>b[1]-a[1]).slice(0,8);
    const rCanvas = document.getElementById("spRoleChart");
    if (rCanvas && roleTop.length) {
        spCharts.role = new Chart(rCanvas.getContext("2d"), {
            type: "bar",
            data: {
                labels: roleTop.map(([k]) => k.length>22 ? k.slice(0,20)+"…" : k),
                datasets: [{ data: roleTop.map(([,v])=>v),
                    backgroundColor: roleTop.map((_,i) => `${accent}${(0.9 - i*0.09).toFixed(2)})`),
                    borderRadius: 6, borderSkipped: false }]
            },
            options: { indexAxis:"y", plugins:{legend:{display:false}},
                scales:{ x:{grid:{display:false}}, y:{grid:{display:false}} },
                responsive:true, maintainAspectRatio:true }
        });
    }

    // ── Top Skills ─────────────────────────────────────────────
    // SKIP: empty, "_", "—", single chars, pure numbers
    const JUNK = new Set(["-", "—", "_", "N/A", "n/a", "None", "none", "NA"]);
    const skillMap = {};
    data.forEach(d => {
        if (!d.skills) return;
        d.skills.split(",").map(s => s.trim()).forEach(s => {
            if (!s || s.length < 2 || JUNK.has(s) || /^[\d\s]+$/.test(s)) return;
            const lowerSkill = s.toLowerCase();
            if (!skillMap[lowerSkill]) {
                skillMap[lowerSkill] = { count: 0, cases: {} };
            }
            skillMap[lowerSkill].count += 1;
            skillMap[lowerSkill].cases[s] = (skillMap[lowerSkill].cases[s] || 0) + 1;
        });
    });

    const resolvedSkillFreq = {};
    Object.entries(skillMap).forEach(([lowerSkill, info]) => {
        let bestCase = "";
        let maxCount = -1;
        Object.entries(info.cases).forEach(([casing, count]) => {
            if (count > maxCount) {
                maxCount = count;
                bestCase = casing;
            }
        });
        resolvedSkillFreq[bestCase] = info.count;
    });

    const skillTop = Object.entries(resolvedSkillFreq).sort((a,b)=>b[1]-a[1]).slice(0,10);
    const sCanvas = document.getElementById("spSkillsChart");
    if (sCanvas && skillTop.length) {
        spCharts.skills = new Chart(sCanvas.getContext("2d"), {
            type: "bar",
            data: {
                labels: skillTop.map(([k])=>k),
                datasets: [{ data: skillTop.map(([,v])=>v),
                    backgroundColor: skillTop.map((_,i) => `${accent}${(0.95-i*0.08).toFixed(2)})`),
                    borderRadius: 6, borderSkipped: false }]
            },
            options: { indexAxis:"y", plugins:{legend:{display:false}},
                scales:{ x:{grid:{display:false}}, y:{grid:{display:false}} },
                responsive:true, maintainAspectRatio:true }
        });
    }

    // ── Top Companies ──────────────────────────────────────────
    const compMap = countBy(data, "company");
    const compTop = Object.entries(compMap).sort((a,b)=>b[1]-a[1]).slice(0,8);
    const cCanvas = document.getElementById("spCompanyChart");
    if (cCanvas && compTop.length) {
        spCharts.company = new Chart(cCanvas.getContext("2d"), {
            type: "bar",
            data: {
                labels: compTop.map(([k])=>k.length>18?k.slice(0,16)+"…":k),
                datasets: [{ data: compTop.map(([,v])=>v),
                    backgroundColor: compTop.map((_,i) => `${accent}${(0.9-i*0.09).toFixed(2)})`),
                    borderRadius: 6, borderSkipped: false }]
            },
            options: { indexAxis:"y", plugins:{legend:{display:false}},
                scales:{ x:{grid:{display:false}}, y:{grid:{display:false}} },
                responsive:true, maintainAspectRatio:true }
        });
    }

    // ── CTC Distribution ───────────────────────────────────────
    const ctcMap = countBy(data, "ctc");
    const ctcTop = Object.entries(ctcMap).filter(([k])=>k).sort((a,b)=>b[1]-a[1]).slice(0,8);
    const ctcCanvas = document.getElementById("spCtcChart");
    if (ctcCanvas && ctcTop.length) {
        spCharts.ctc = new Chart(ctcCanvas.getContext("2d"), {
            type: "doughnut",
            data: {
                labels: ctcTop.map(([k])=>k),
                datasets: [{ data: ctcTop.map(([,v])=>v),
                    backgroundColor: ctcTop.map((_,i) => `${accent}${(0.9-i*0.09).toFixed(2)})`),
                    borderWidth: 2, borderColor: "#fff" }]
            },
            options: { plugins:{ legend:{ position:"bottom", labels:{ boxWidth:12, font:{size:11} } } },
                responsive:true, maintainAspectRatio:true }
        });
    }

    // ── Seniority ──────────────────────────────────────────────
    const senMap = countBy(data, "seniority");
    const senTop = Object.entries(senMap).filter(([k])=>k).sort((a,b)=>b[1]-a[1]);
    const senCanvas = document.getElementById("spSeniorityChart");
    if (senCanvas && senTop.length) {
        spCharts.seniority = new Chart(senCanvas.getContext("2d"), {
            type: "doughnut",
            data: {
                labels: senTop.map(([k])=>k),
                datasets: [{ data: senTop.map(([,v])=>v),
                    backgroundColor: senTop.map((_,i) => `${accent}${(0.9-i*0.1).toFixed(2)})`),
                    borderWidth: 2, borderColor: "#fff" }]
            },
            options: { plugins:{ legend:{ position:"bottom", labels:{ boxWidth:12, font:{size:11} } } },
                responsive:true, maintainAspectRatio:true }
        });
    }
}


// School chart with selected school highlighted (opacity dimming on others)
function renderSchoolChartHighlighted(data, selectedSchool) {
    const canvas = document.getElementById("schoolChart");
    if (!canvas) return;

    const map = countBy(data, "school");
    const labels = Object.keys(map);
    const values = Object.values(map);

    const existingChart = Chart.getChart(canvas);
    if (existingChart) existingChart.destroy();

    const SCHOOL_COLORS = {
        "School of Engineering (SOE)": "rgba(37, 99, 235, 1)",   // Solid tech blue
        "School of Business (SOB)":    "rgba(217, 119, 6, 1)",    // Solid warm amber
        "School of Science (SOS)":     "rgba(5, 150, 105, 1)",    // Solid deep emerald
        "School of Humanity (SOH)":    "rgba(219, 39, 119, 1)",   // Solid rose pink
        "School of Law (SOL)":         "rgba(124, 58, 237, 1)",   // Solid royal purple
    };
    const SCHOOL_COLORS_DIM = {
        "School of Engineering (SOE)": "rgba(37, 99, 235, 0.35)",  // Clearly visible dim blue
        "School of Business (SOB)":    "rgba(217, 119, 6, 0.35)",   // Clearly visible dim amber
        "School of Science (SOS)":     "rgba(5, 150, 105, 0.35)",   // Clearly visible dim emerald
        "School of Humanity (SOH)":    "rgba(219, 39, 119, 0.35)",  // Clearly visible dim rose
        "School of Law (SOL)":         "rgba(124, 58, 237, 0.35)",  // Clearly visible dim purple
    };

    const bgColors = labels.map(label => {
        if (!selectedSchool) return SCHOOL_COLORS[label] || "rgba(99,102,241,1)";
        return label === selectedSchool
            ? SCHOOL_COLORS[label] || "rgba(99,102,241,1)"
            : SCHOOL_COLORS_DIM[label] || "rgba(99,102,241,0.35)";
    });

    const ctx = canvas.getContext("2d");
    chartInstances.school = new Chart(ctx, {
        type: "doughnut",
        data: {
            labels,
            datasets: [{
                data: values,
                backgroundColor: bgColors,
                borderColor: "#fff",
                borderWidth: selectedSchool ? labels.map(l => l === selectedSchool ? 3 : 1) : 3,
                hoverOffset: 10,
            }],
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            cutout: "60%",
            plugins: {
                legend: {
                    position: "bottom",
                    labels: {
                        usePointStyle: true,
                        pointStyle: "circle",
                        boxWidth: 8,
                        boxHeight: 8,
                        padding: 12,
                        font: { family: "'Inter', sans-serif", size: 10, weight: "600" },
                        color: (ctx) => {
                            if (!selectedSchool) return "#4b5563";
                            return ctx.text === selectedSchool ? "#1e1b4b" : "#c4c9d4";
                        }
                    }
                },
                tooltip: {
                    backgroundColor: "rgba(30, 27, 75, 0.95)",
                    titleColor: "#ffffff",
                    titleFont: { family: "'Outfit', sans-serif", size: 12, weight: "700" },
                    bodyColor: "#c7d2fe",
                    bodyFont: { family: "'Inter', sans-serif", size: 11, weight: "500" },
                    padding: 10,
                    cornerRadius: 8,
                    displayColors: true,
                    boxWidth: 8,
                    boxHeight: 8,
                    borderWidth: 1,
                    borderColor: "rgba(99, 102, 241, 0.15)",
                    callbacks: {
                        label: ctx => {
                            const pct = ((ctx.parsed / data.length) * 100).toFixed(0);
                            const isActive = selectedSchool && ctx.label === selectedSchool;
                            return ` ${isActive ? "▶ " : ""}${ctx.parsed} jobs (${pct}%)`;
                        }
                    }
                },
            },
        },
    });
}


function updateSchoolContextBanner(school, filtered) {
    const banner = document.getElementById("schoolContextBanner");
    const nameEl = document.getElementById("schoolContextName");
    const descEl = document.getElementById("schoolContextDesc");
    const kpisEl = document.getElementById("schoolContextKpis");
    if (!banner) return;

    if (!school) {
        banner.classList.add("hidden");
        return;
    }

    const meta = SCHOOL_META[school] || {};
    banner.classList.remove("hidden");
    banner.style.setProperty("--school-color", meta.color || "#6366f1");
    if (nameEl) nameEl.textContent = school;
    if (descEl) descEl.textContent = meta.desc || "Showing roles for this school";

    // Build mini KPIs
    if (kpisEl) {
        const companies = [...new Set(filtered.map(d => d.company).filter(Boolean))].length;
        const roles = [...new Set(filtered.map(d => d.role).filter(Boolean))].length;
        kpisEl.innerHTML = `
            <div class="school-kpi-item">
                <span class="school-kpi-val">${filtered.length}</span>
                <span class="school-kpi-lbl">Jobs</span>
            </div>
            <div class="school-kpi-item">
                <span class="school-kpi-val">${companies}</span>
                <span class="school-kpi-lbl">Companies</span>
            </div>
            <div class="school-kpi-item">
                <span class="school-kpi-val">${roles}</span>
                <span class="school-kpi-lbl">Roles</span>
            </div>
        `;
    }
}

function updateFilteredCount(school, filtered) {
    const el = document.getElementById("filteredCount");
    if (!el) return;
    if (school) {
        el.textContent = `${filtered.length} result${filtered.length !== 1 ? "s" : ""} in ${SCHOOL_META[school]?.abbr || school}`;
        el.classList.remove("hidden");
    } else {
        el.classList.add("hidden");
    }
}


// ── Event Listeners ──────────────────────────────────────────
document.getElementById("dashSearch")?.addEventListener("input", () => {
    const filtered = getFilteredData();
    renderTable(filtered);
    updateFilteredCount(activeSchoolFilter, filtered);
});
document.getElementById("seniorityFilter")?.addEventListener("change", () => {
    const filtered = getFilteredData();
    renderTable(filtered);
    updateFilteredCount(activeSchoolFilter, filtered);
});
document.getElementById("schoolFilter")?.addEventListener("change", () => {
    activeSchoolFilter = document.getElementById("schoolFilter").value;
    const filtered = getFilteredData();
    renderTable(filtered);
    updateSchoolContextBanner(activeSchoolFilter, filtered);
    updateFilteredCount(activeSchoolFilter, filtered);
});
document.querySelectorAll(".dash-table th[data-sort]").forEach(th => {
    th.addEventListener("click", () => {
        const key = th.dataset.sort;
        if (currentSort.key === key) {
            currentSort.asc = !currentSort.asc;
        } else {
            currentSort = { key, asc: true };
        }
        document.querySelectorAll(".dash-table th .sort-icon").forEach(icon => icon.textContent = "↕");
        th.querySelector(".sort-icon").textContent = currentSort.asc ? "↑" : "↓";
        renderTable(getFilteredData());
    });
});

// Refresh button — always force a full re-render by resetting the hash
document.getElementById("refreshDashboard")?.addEventListener("click", () => {
    lastDataHash = "__UNINITIALISED__"; // Force re-render even if data looks same
    loadDashboardData(true);
});

// Auto-refresh toggle
document.getElementById("toggleAutoRefresh")?.addEventListener("click", () => {
    autoRefreshEnabled = !autoRefreshEnabled;
    updateAutoRefreshUI();
    if (autoRefreshEnabled) {
        startPolling();
    } else {
        stopPolling();
    }
});

// Retry button
document.getElementById("dashRetryBtn")?.addEventListener("click", () => {
    hideError();
    loadDashboardData(true);
});

// ── Polling ──────────────────────────────────────────────────
function startPolling() {
    stopPolling();
    if (autoRefreshEnabled) {
        pollTimer = setInterval(() => loadDashboardData(false), SHEET_CONFIG.pollInterval);
    }
}

function stopPolling() {
    if (pollTimer) {
        clearInterval(pollTimer);
        pollTimer = null;
    }
}

// ── Toast Notification for New Data ──────────────────────────
function showNewDataToast(count) {
    // Remove existing toast if any
    const existing = document.querySelector('.dash-toast');
    if (existing) existing.remove();

    const toast = document.createElement('div');
    toast.className = 'dash-toast';
    toast.innerHTML = `
        <span class="material-symbols-rounded">update</span>
        <span>Dashboard updated — ${count} application${count !== 1 ? 's' : ''} loaded</span>
    `;
    document.body.appendChild(toast);

    // Trigger animation
    requestAnimationFrame(() => toast.classList.add('show'));

    // Auto-dismiss after 4 seconds
    setTimeout(() => {
        toast.classList.remove('show');
        setTimeout(() => toast.remove(), 400);
    }, 4000);
}

// ── Render all dashboard elements ────────────────────────────
function renderDashboard(data, isAutoRefresh = false) {
    populateSeniorityFilter(data);
    populateSchoolFilter(data);

    // If a school filter was active, preserve it across reloads
    if (activeSchoolFilter) {
        // Re-apply the full school filter (updates KPIs + all charts + table)
        applySchoolFilter(activeSchoolFilter);
    } else {
        // Full render with all data
        renderDashboardCharts(data);
        renderTable(sortData(data, currentSort.key, currentSort.asc));
    }

    // Show visual feedback when data updates
    if (isAutoRefresh) {
        showNewDataToast(data.length);
        const tableSection = document.querySelector('.dash-table-section');
        if (tableSection) {
            tableSection.classList.add('data-pulse');
            setTimeout(() => tableSection.classList.remove('data-pulse'), 1200);
        }
    }
}


// ── Custom Live Sheet Renderer (Bypasses Google Caching) ────────────────
function renderLiveSheet(table) {
    const container = document.getElementById("liveSheetContainer");
    if (!container) return;

    if (!table || !table.cols || table.cols.length === 0) {
        container.innerHTML = `
            <div class="sheet-empty-state">
                <span class="material-symbols-rounded">table_chart</span>
                <p>Google Sheet is currently empty.</p>
                <small>Once JD data is uploaded, it will render here in real-time.</small>
            </div>`;
        return;
    }

    const cols = table.cols;
    const rows = table.rows || [];

    let html = `<div class="sheet-table-scroll"><table class="sheet-table-grid">`;
    
    // Header Row
    html += `<thead><tr>`;
    html += `<th class="sheet-header-cell sheet-index-col"></th>`;
    cols.forEach((col, idx) => {
        // Convert index to Excel column label (A, B, C... Z, AA, AB...)
        let colLetter = "";
        let temp = idx;
        while (temp >= 0) {
            colLetter = String.fromCharCode((temp % 26) + 65) + colLetter;
            temp = Math.floor(temp / 26) - 1;
        }
        html += `<th class="sheet-header-cell">
            <div class="sheet-col-letter">${colLetter}</div>
            <div class="sheet-col-label" title="${col.label || ''}">${col.label || ''}</div>
        </th>`;
    });
    html += `</tr></thead>`;

    // Body Rows
    html += `<tbody>`;
    
    if (rows.length === 0) {
        // Empty Sheet Grid placeholder
        for (let r = 0; r < 12; r++) {
            html += `<tr>`;
            html += `<td class="sheet-index-cell">${r + 1}</td>`;
            cols.forEach(() => {
                html += `<td class="sheet-data-cell sheet-cell-empty"></td>`;
            });
            html += `</tr>`;
        }
    } else {
        rows.forEach((row, rowIdx) => {
            html += `<tr>`;
            html += `<td class="sheet-index-cell">${rowIdx + 1}</td>`;
            
            const cells = row.c || [];
            cols.forEach((_, colIdx) => {
                const cell = cells[colIdx];
                const val = cell ? (cell.f || cell.v || "") : "";
                const isUrl = typeof val === 'string' && (val.startsWith('http://') || val.startsWith('https://'));
                
                if (isUrl) {
                    html += `<td class="sheet-data-cell"><a href="${val}" target="_blank" rel="noopener">${val}</a></td>`;
                } else {
                    html += `<td class="sheet-data-cell" title="${val}">${val}</td>`;
                }
            });
            html += `</tr>`;
        });
        
        // Add a few extra blank rows at the bottom for spreadsheet styling
        for (let r = 0; r < 6; r++) {
            html += `<tr>`;
            html += `<td class="sheet-index-cell">${rows.length + r + 1}</td>`;
            cols.forEach(() => {
                html += `<td class="sheet-data-cell sheet-cell-empty"></td>`;
            });
            html += `</tr>`;
        }
    }

    html += `</tbody></table></div>`;
    container.innerHTML = html;
}


// ── Load data from Google Sheets ─────────────────────────────
async function loadDashboardData(showLoadingState = true) {
    if (showLoadingState) showLoading();
    hideError();

    try {
        const { data, table, _needsRedeploy } = await fetchSheetData();
        const newHash = hashData(data);

        // Show redeploy warning if Apps Script hasn't been updated yet
        showRedeployWarning(_needsRedeploy);

        // Re-render whenever data actually changed OR on the very first load
        if (newHash !== lastDataHash) {
            const isAutoRefresh = lastDataHash !== "__UNINITIALISED__" && !showLoadingState;
            SHEET_DATA = data;
            lastDataHash = newHash;
            renderDashboard(data, isAutoRefresh);
            renderLiveSheet(table);
        }

        updateLastUpdated();
        hideLoading();
    } catch (err) {
        console.error("Dashboard fetch error:", err);
        hideLoading();
        showError(err.message);

        // If we have stale data, keep showing it
        if (SHEET_DATA.length === 0) {
            // No data at all - show empty state
        }
    }
}

// ── Redeploy Warning Banner ───────────────────────────────────
function showRedeployWarning(show) {
    let banner = document.getElementById('redeployBanner');
    if (!banner) {
        banner = document.createElement('div');
        banner.id = 'redeployBanner';
        banner.style.cssText = [
            'position:fixed', 'top:72px', 'left:50%', 'transform:translateX(-50%)',
            'background:linear-gradient(135deg,#b45309,#92400e)',
            'color:#fff', 'padding:12px 20px', 'border-radius:12px',
            'font-size:13px', 'font-weight:600', 'z-index:9999',
            'box-shadow:0 4px 24px rgba(0,0,0,.5)',
            'display:flex', 'align-items:center', 'gap:12px',
            'max-width:640px', 'text-align:left'
        ].join(';');
        banner.innerHTML = `
            <span style="font-size:20px">⚠️</span>
            <span><strong>Dashboard is showing cached data.</strong><br>
            The Google Apps Script needs to be redeployed with the updated
            <code style="background:rgba(255,255,255,.2);padding:1px 6px;border-radius:4px">doGet</code>
            function so live sheet data can be read directly.</span>
            <button onclick="this.parentElement.style.display='none'"
              style="background:rgba(255,255,255,.2);border:none;color:#fff;padding:5px 12px;
                     border-radius:8px;cursor:pointer;font-size:12px;white-space:nowrap;flex-shrink:0">
              Got it
            </button>`;
        document.body.appendChild(banner);
    }
    banner.style.display = show ? 'flex' : 'none';
}


// ── Initialize Dashboard ──────────────────────────────
async function initDashboard() {
    updateAutoRefreshUI();
    initSchoolPillListeners();
    await loadDashboardData(true);
    startPolling();

    // ── Clear All Data button ──────────────────────────
    const clearBtn = document.getElementById('clearDashboard');
    if (clearBtn) {
        clearBtn.addEventListener('click', async () => {
            const confirmed = confirm(
                '⚠️ Clear ALL data from the Google Sheet?\n\n' +
                'This will permanently delete every row from the sheet ' +
                'and reset the dashboard to zero. This cannot be undone.'
            );
            if (!confirmed) return;

            clearBtn.disabled = true;
            clearBtn.textContent = 'Clearing…';

            try {
                const res  = await fetch('/api/clear-sheet', { method: 'POST' });
                const json = await res.json();

                if (json.success) {
                    // Immediately wipe local state and re-render empty dashboard
                    SHEET_DATA = [];
                    lastDataHash = '__UNINITIALISED__';
                    renderDashboard([], false);
                    renderLiveSheet({ cols: [], rows: [] });
                    showRedeployWarning(false);
                    alert('✅ Sheet cleared! ' + (json.rowsDeleted || 0) + ' rows deleted.');
                } else {
                    // clearSheet not yet deployed — guide the user
                    alert(
                        '⚠️ Could not clear automatically.\n\n' +
                        'Please do ONE of these:\n' +
                        '1. In the Apps Script editor, run the clearAllData() function (no deploy needed)\n' +
                        '2. OR open Google Sheets → select rows 2 onward → right-click → Delete rows'
                    );
                }
            } catch (err) {
                alert('Error: ' + err.message);
            } finally {
                clearBtn.disabled = false;
                clearBtn.innerHTML = '<span class="material-symbols-rounded">delete_sweep</span> Clear All Data';
                // Refresh from server
                loadDashboardData(false);
            }
        });
    }
}

// ── Expose API for cross-script communication ────────────────
// Allows script.js to trigger a dashboard refresh after JD analysis
window.dashboardAPI = {
    refresh: (showLoading = false) => loadDashboardData(showLoading),
    isInitialized: () => dashboardInitialized,
    markDirty: () => { lastDataHash = "__UNINITIALISED__"; } // Force re-render on next fetch
};

